package com.perscholas.Classified.Spring.repository.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import com.perscholas.Classified.Spring.model.User;
import com.perscholas.Classified.Spring.repository.UserRepository;


	@Repository("mariaDbUserRepository")
	public class UserRepositoryImpl implements UserRepository {

		@Autowired
		private NamedParameterJdbcTemplate mariaDbJdbcTemplate;

		@Override
		public Integer registerUser(User user) {
			Integer id = -1;
			/* The class MapSqlParameterSource behaves much like a Map and holds 
			 * key-value pairs. The keys can be included in a query string to 
			 * accept values associated with the keys such as illustrated in the 
			 * "createCourseSql" string below. */
			MapSqlParameterSource params = new MapSqlParameterSource();
			
			params.addValue("userName", user.getUserName());
			params.addValue("password", user.getPassword());
			String createUserSql = "insert into register (userName, password) values "
					+ "(:userName, :password)";
			
			/* The KeyHolder instance will receive the primary key generated by 
			 * the database.*/
			KeyHolder keyHolder = new GeneratedKeyHolder();
			Integer createResult = mariaDbJdbcTemplate.update(createUserSql, 
					params, keyHolder);
			/* The JdbcTemplate "update" method returns the number of rows 
			 * affected. If the number is 0, then it indicates the insert 
			 * attempt failed. */
			if (createResult > 0) {
				/* The Database returns a BigInteger that needs to be cast to an 
				 * int or Integer. */
				id = keyHolder.getKey().intValue();
			}
			return id;
		}

		@Override
		public Boolean getUser(String userName) {
			// TODO Auto-generated method stub
			return null;
		}

		
		
				
}
